feat: improve error handling on missing controller & serializer files
We now have the following messages when a file is missing

```
Error: Could not resolve model by name 'user'
Error: Could not resolve controller by name 'users'
Error: Could not resolve serializer by name 'users'
```

Fixes #104